name: Build and Deploy to SaladCloud

on:
  push:
    paths:
      - 'Dockerfile'
      - '*.py'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: docker.io/richardxgf/actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        id: vars
        run: |
          TAG=$(python3 generate_tag.py)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SaladCloud SDK and deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy via SaladCloud SDK
        env:
          SALAD_API_KEY: ${{ secrets.SALAD_API_KEY }}
        run: |
          python salad_deploy.py --image $IMAGE_NAME:$TAG
